Developers: add LiaBTC contracts documentation
CoinFabrik/alex-lisalab-io-docs pull request #1
Opened 2024-12-04 16:17 UTC by sofinico

## Description 

Added LiaBTC technical documents. Impacts on https://docs.lisalab.io/. This branch is live at a temporary URL [here](https://coinfabrik.gitbook.io/lisa/developers/contracts).

### Changes

1. Created the **Contracts** page under the **Developers** group (see [Gitbook page groups](https://docs.gitbook.com/content-editor/editor/content-structure/content-in-a-space#page-groups)).

2. Added technical documentation for the contracts:

    - `liabtc-mint-endpoint.clar`
    - `liabtc-mint-registry.clar`
    - `token-liabtc.clar`
    - `token-vliabtc.clar`
    
3. Updated the `SUMMARY.md` accordingly. 

### Following work

- Add XLink Staking Manager (`xlink-staking.clar`) documentation. Location to be determined between LISA or XLink Docs.

- Add content to the main **Contracts** page to serve as both an index and an overarching overview of the LISA on-chain ecosystem. This will help the reader to introduce content and present each contract, not in isolation, but as a part of a system.

2024-12-11 16:36 UTC, tenuki approved these changes

2024-12-11 16:36 UTC, tenuki commented on developers/contracts/liabtc-mint-endpoint.md
> +- User transfers `aBTC` to be staked in the liquid pool.
se lo llama _liquid pool_ o debería ser: _liquidity pool_ ?

2024-12-11 16:36 UTC, tenuki commented on developers/contracts/liabtc-mint-endpoint.md
> +# liabtc-mint-endpoint
I'm not sure if this is a good title for these documents.. perhaps   ... `liabtc-mint-endpoint` contract ?

2024-12-11 16:36 UTC, tenuki commented on developers/contracts/liabtc-mint-endpoint.md
> +- The `aBTC` are sent from the Staking Manager to the registry, which will hold the funds until the request is either finalized or revoked.
Deberíamos referirnos a la registry como una entidad de tanto peso como el Staking Manager que está con mayúsculas?

2024-12-11 16:36 UTC, tenuki commented on developers/contracts/liabtc-mint-endpoint.md
> +- The amount of `aBTC` is unstaked from the Staking Manager.
When you say "The amount of aBTC" you mean: "The **same** amount ..." ?

2024-12-11 16:36 UTC, tenuki commented on developers/contracts/liabtc-mint-endpoint.md
> +- The unstaked `aBTC` is transferred from the `xlink-staking` to the `liabtc-mint-endpoint` and then to the[`liabtc-mint-registry`][r] to be holded until finalization o revoke.
I feel this sentence is already "half told" in the sentence above. Both "actions" aren't really two different actions, the tell the same.  I would be more explicit on where Staking Manager is on xlink-staking or other file, or wouldn't mention (files or contacts) or components, or would mention them all saying what is in which one, all in the same sentence..

2024-12-11 16:36 UTC, tenuki commented on developers/contracts/liabtc-mint-endpoint.md
> +Revokes a burn request. Only the requestor (`requested-by` field of the request) can call this function. The registry returns the funds back to user as in `finalize-request`, with the key difference
`REVOKED` or `REVOKE` ?  above you said `REVOKE`.

2024-12-11 16:36 UTC, tenuki commented on developers/contracts/liabtc-mint-endpoint.md
> +Finalizes a burn request by transferring the `aBTC` from the registry to the user (`requested-by` field of the request). Request is set as `FINALIZED`. Anyone can call.
"Anyone can call." Too informal and non clear.
"This function can be called by any user."   or  "This function can be called by any user including those who did not initiate the burn request."

2024-12-11 16:36 UTC, tenuki commented on developers/contracts/token-liabtc.md
> +The `LiaBTC` balance of each user, accessible via the [`get-balance`](#get-balance) function, is automatically adjusted on each rebase, without involving an explicit token transfer. In a scenario whe
why _re_ injected instead of just injected?

2024-12-11 16:36 UTC, tenuki commented on developers/contracts/token-liabtc.md
> +The above equation can be generalized for an arbitrary amount of shares
The formula doesn't change from the one above.. nevertheless I don't think this to be a problem...

Please add : after ""..amount of shares"

2024-12-11 16:36 UTC, tenuki commented on developers/contracts/token-liabtc.md
> +The rebasing nature of `LiaBTC` is implemented via the "shares" concept. The contract tracks and stores each user's share of an external reserve. By holding shares, users hold a portion of the total
Is it clear: "The reserve is tracked by the..." ?

I mean, what is tracked is reserve's amount or balance..

2024-12-11 16:36 UTC, tenuki commented on developers/contracts/token-liabtc.md
> +- **Reserve** is the current total value of `aBTC` staked, backed by the `BTC` staked at Babylon and their corresponding staking rewards which were converted to `BTC` and restaked.
"..current total value of `aBTC`  ..."       s/value/amount/   ?

2024-12-11 16:36 UTC, tenuki commented on developers/contracts/liabtc-mint-registry.md
> +Map that stores the burn requests used by the [`liabtc-mint-endpoint`][mint].
Segun otros docs y comentarios, esto no podría ser usado por otros componentes (que se lo propongan) también? Deberíamos hacer algun comentario sobre esto?  Quizas mencionarlo aca?   Va.. digo.. si es asi.. entonces esa oracion esta incompleta .. liabtc-mint-endpoing and/or others..

2024-12-11 16:36 UTC, tenuki commented on developers/contracts/liabtc-mint-registry.md
> +#### `REVOKED`
En liabtc-mint-endpoint hablabamos de REVOKE en lugar de REVOKED... cual esta bien de los dos?

2024-12-11 16:37 UTC, tenuki requested changes
please see comments..

2024-12-12 19:56 UTC, sofinico commented on developers/contracts/liabtc-mint-endpoint.md
> +- User transfers `aBTC` to be staked in the liquid pool.
Buena observación. Lo correcto sería _liquid staking pool_. No es un pool de liquidez sino que es un pool de staking líquido. Así entiendo que se llaman estos pools de staking donde se van agregando las rewards y posibilitan la creación de los _rebasing tokens_. De hecho, LISA se autodenomina "Liquid Staking Protocol". Más info en https://chain.link/education-hub/liquid-staking#what-is-liquid-staking.

2024-12-12 19:57 UTC, sofinico commented on developers/contracts/liabtc-mint-endpoint.md
> +- User transfers `aBTC` to be staked in the liquid pool.
Cambio hecho.

2024-12-12 20:01 UTC, sofinico commented on developers/contracts/liabtc-mint-endpoint.md
> +# liabtc-mint-endpoint
Mhm... es discutible. Me gusta el minimalismo de poner sólo el nombre. Está bajo la carpeta contracts y en la location y descripción menciono siempre que es un contrato. Pero tampoco me molestaría cambiarlo... si te parece, podemos pasar a modificar todos los títulos que están tipo:

# liabtc-mint-endpoint

a:

# `liabtc-mint-endpoint` contract 

Decime qué opinás.

2024-12-12 20:03 UTC, sofinico commented on developers/contracts/liabtc-mint-endpoint.md
> +- The amount of `aBTC` is unstaked from the Staking Manager.
Changed.

2024-12-12 20:06 UTC, sofinico commented on developers/contracts/liabtc-mint-endpoint.md
> +- The unstaked `aBTC` is transferred from the `xlink-staking` to the `liabtc-mint-endpoint` and then to the[`liabtc-mint-registry`][r] to be holded until finalization o revoke.
Changed 👌

2024-12-12 20:13 UTC, sofinico commented on developers/contracts/liabtc-mint-endpoint.md
> +Revokes a burn request. Only the requestor (`requested-by` field of the request) can call this function. The registry returns the funds back to user as in `finalize-request`, with the key difference
La constante se llama `REVOKED` en el contrato, así que corregí una ocurrencia donde lo puse mal :)

2024-12-12 20:15 UTC, sofinico commented on developers/contracts/liabtc-mint-endpoint.md
> +Finalizes a burn request by transferring the `aBTC` from the registry to the user (`requested-by` field of the request). Request is set as `FINALIZED`. Anyone can call.
Done.

2024-12-12 20:19 UTC, sofinico commented on developers/contracts/token-liabtc.md
> +The `LiaBTC` balance of each user, accessible via the [`get-balance`](#get-balance) function, is automatically adjusted on each rebase, without involving an explicit token transfer. In a scenario whe
Me gusta la idea de que las rewards son re-insertadas al mismo protocolo que ls generó. Diría injected para el caso donde el usuario hace stake: se inyecta capital. En el caso de las rewards, se re-inyecta porque se re-invierte. Tiene sentido? Si es muy rebuscado le saco el "re". Avisame. Entiendo que la palabra en inglés existe.

2024-12-12 20:22 UTC, sofinico commented on developers/contracts/token-liabtc.md
> +The above equation can be generalized for an arbitrary amount of shares
Exacto, la ecuación no cambia, pero me parecía piola aclarar que no sirve sólo para los balances de los usuarios sino más general. Si te parece muy naive la aclaración fleto esa parte. Avisame.

2024-12-12 20:26 UTC, sofinico commented on developers/contracts/token-liabtc.md
> +The rebasing nature of `LiaBTC` is implemented via the "shares" concept. The contract tracks and stores each user's share of an external reserve. By holding shares, users hold a portion of the total
Cambiado, y le cambié unas palabritas más al párrafo.

2024-12-12 20:28 UTC, sofinico commented on developers/contracts/token-liabtc.md
> +- **Reserve** is the current total value of `aBTC` staked, backed by the `BTC` staked at Babylon and their corresponding staking rewards which were converted to `BTC` and restaked.
Changed _value_ for _amount_.

2024-12-12 20:33 UTC, sofinico commented on developers/contracts/liabtc-mint-registry.md
> +Map that stores the burn requests used by the [`liabtc-mint-endpoint`][mint].
Yo entiendo que el `liabtc-mint-registry` está hecho para funcionar con el `liabtc-mint-endpoint` y con ninguno más. Eso en tanto propósito de uso. Ahora bien, esto no es una restricción que se ve en el código, dada la autenticación de roles que usa ALEX, cualquier extensión podría modificar ese mapa. 

Cambio a _typically_ used en lugar de sólo used.

2024-12-12 20:33 UTC, sofinico commented on developers/contracts/liabtc-mint-registry.md
> +#### `REVOKED`
Respondido arriva, `REVOKED` es la correcta jeje

2024-12-12 20:34 UTC, sofinico commented on developers/contracts/liabtc-mint-endpoint.md
> +- The `aBTC` are sent from the Staking Manager to the registry, which will hold the funds until the request is either finalized or revoked.
Es una buena pregunta... pensemos.

2024-12-13 09:03 UTC, sofinico commented on developers/contracts/liabtc-mint-endpoint.md
> +# liabtc-mint-endpoint
Resolvimos atacar esto cuando hagamos un review de formato del template v.0.1.1.

2024-12-13 09:14 UTC, sofinico commented on developers/contracts/liabtc-mint-endpoint.md
> +- The `aBTC` are sent from the Staking Manager to the registry, which will hold the funds until the request is either finalized or revoked.
Solved.

2024-12-13 11:56 UTC, tenuki commented on developers/contracts/liabtc-mint-endpoint.md
> +- User transfers `aBTC` to be staked in the liquid pool.
gracias!

2024-12-13 11:58 UTC, tenuki commented on developers/contracts/token-liabtc.md
> +The above equation can be generalized for an arbitrary amount of shares
nah.. esta bien.. misma cuenta pero los nombres explican otras situaciones.

2024-12-13 11:58 UTC, tenuki commented on developers/contracts/liabtc-mint-registry.md
> +Map that stores the burn requests used by the [`liabtc-mint-endpoint`][mint].
Ah. ok entiendo! Gracias!

2024-12-13 11:59 UTC, tenuki approved these changes

2024-12-13 12:16 UTC, sofinico commented
Se creó la rama `devs/liabtc-contracts-reviewed` a partir de esta rama y se creó el PR de delivery https://github.com/lisalab-io/docs/pull/4. El flujo de trabajo no fue el ideal, lo correcto sería haber hecho este PR con source `devs/liabtc-contacts` y target `devs/liabtc-contacts-reviewed`.

2024-12-13 12:16 UTC, closed without merging